#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 8b93847
#
Name     : sox
Version  : 14.4.2
Release  : 22
URL      : https://sourceforge.net/projects/sox/files/sox/14.4.2/sox-14.4.2.tar.bz2
Source0  : https://sourceforge.net/projects/sox/files/sox/14.4.2/sox-14.4.2.tar.bz2
Summary  : Audio file format and effects library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: sox-bin = %{version}-%{release}
Requires: sox-lib = %{version}-%{release}
Requires: sox-license = %{version}-%{release}
Requires: sox-man = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-configure
BuildRequires : file-dev
BuildRequires : libsndfile-dev
BuildRequires : pkgconfig(flac)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(opusfile)
BuildRequires : pkgconfig(vorbis)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: CVE-2017-11332.patch
Patch2: CVE-2017-11358.patch
Patch3: CVE-2017-11359.patch
Patch4: CVE-2017-15370.patch
Patch5: CVE-2017-15371.patch
Patch6: CVE-2017-15372.patch
Patch7: CVE-2017-15642.patch
Patch8: CVE-2017-18189.patch
Patch9: CVE-2019-8354.patch
Patch10: CVE-2019-8356.patch
Patch11: CVE-2019-8357.patch
Patch12: CVE-2019-13590.patch

%description
SoX: Sound eXchange
===================
SoX (Sound eXchange) is the Swiss Army knife of sound processing tools: it
can convert sound files between many different file formats & audio devices,
and can apply many sound effects & transformations, as well as doing basic
analysis and providing input to more capable analysis and plotting tools.

%package bin
Summary: bin components for the sox package.
Group: Binaries
Requires: sox-license = %{version}-%{release}

%description bin
bin components for the sox package.


%package dev
Summary: dev components for the sox package.
Group: Development
Requires: sox-lib = %{version}-%{release}
Requires: sox-bin = %{version}-%{release}
Provides: sox-devel = %{version}-%{release}
Requires: sox = %{version}-%{release}

%description dev
dev components for the sox package.


%package lib
Summary: lib components for the sox package.
Group: Libraries
Requires: sox-license = %{version}-%{release}

%description lib
lib components for the sox package.


%package license
Summary: license components for the sox package.
Group: Default

%description license
license components for the sox package.


%package man
Summary: man components for the sox package.
Group: Default

%description man
man components for the sox package.


%prep
%setup -q -n sox-14.4.2
cd %{_builddir}/sox-14.4.2
%patch -P 1 -p1
%patch -P 2 -p1
%patch -P 3 -p1
%patch -P 4 -p1
%patch -P 5 -p1
%patch -P 6 -p1
%patch -P 7 -p1
%patch -P 8 -p1
%patch -P 9 -p1
%patch -P 10 -p1
%patch -P 11 -p1
%patch -P 12 -p1
pushd ..
cp -a sox-14.4.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1739391726
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --with-png \
--with-pulseaudio \
--with-oggvorbis \
--with-flac
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --with-png \
--with-pulseaudio \
--with-oggvorbis \
--with-flac
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -fstack-protector-strong -fzero-call-used-regs=used -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1739391726
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sox
cp %{_builddir}/sox-%{version}/COPYING %{buildroot}/usr/share/package-licenses/sox/80e5c5a14b56473afb672af36c556e8416cf93a0 || :
cp %{_builddir}/sox-%{version}/LICENSE.GPL %{buildroot}/usr/share/package-licenses/sox/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/sox-%{version}/LICENSE.LGPL %{buildroot}/usr/share/package-licenses/sox/caeb68c46fa36651acf592771d09de7937926bb3 || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/sox
/usr/bin/play
/usr/bin/rec
/usr/bin/sox
/usr/bin/soxi

%files dev
%defattr(-,root,root,-)
/usr/include/sox.h
/usr/lib64/libsox.so
/usr/lib64/pkgconfig/sox.pc
/usr/share/man/man3/libsox.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libsox.so.3.0.0
/usr/lib64/libsox.so.3
/usr/lib64/libsox.so.3.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sox/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/sox/80e5c5a14b56473afb672af36c556e8416cf93a0
/usr/share/package-licenses/sox/caeb68c46fa36651acf592771d09de7937926bb3

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/play.1
/usr/share/man/man1/rec.1
/usr/share/man/man1/sox.1
/usr/share/man/man1/soxi.1
/usr/share/man/man7/soxeffect.7
/usr/share/man/man7/soxformat.7
