#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : sox
Version  : 14.4.2
Release  : 3
URL      : https://sourceforge.net/projects/sox/files/sox/14.4.2/sox-14.4.2.tar.bz2
Source0  : https://sourceforge.net/projects/sox/files/sox/14.4.2/sox-14.4.2.tar.bz2
Summary  : Audio file format and effects library
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: sox-bin
Requires: sox-lib
Requires: sox-doc
BuildRequires : alsa-lib-dev
BuildRequires : cmake
BuildRequires : libsndfile-dev
BuildRequires : pkgconfig(flac)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(opusfile)
BuildRequires : pkgconfig(vorbis)

%description
SoX: Sound eXchange
===================
SoX (Sound eXchange) is the Swiss Army knife of sound processing tools: it
can convert sound files between many different file formats & audio devices,
and can apply many sound effects & transformations, as well as doing basic
analysis and providing input to more capable analysis and plotting tools.

%package bin
Summary: bin components for the sox package.
Group: Binaries

%description bin
bin components for the sox package.


%package dev
Summary: dev components for the sox package.
Group: Development
Requires: sox-lib
Requires: sox-bin
Provides: sox-devel

%description dev
dev components for the sox package.


%package doc
Summary: doc components for the sox package.
Group: Documentation

%description doc
doc components for the sox package.


%package lib
Summary: lib components for the sox package.
Group: Libraries

%description lib
lib components for the sox package.


%prep
%setup -q -n sox-14.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1517338205
%configure --disable-static --with-png \
--with-pulseaudio \
--with-oggvorbis \
--with-flac
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1517338205
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/play
/usr/bin/rec
/usr/bin/sox
/usr/bin/soxi

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libsox.so
/usr/lib64/pkgconfig/sox.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
%doc /usr/share/man/man7/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libsox.so.3
/usr/lib64/libsox.so.3.0.0
